n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
n4 = int(input('Digite o último número: '))
digitados = (n1, n2, n3, n4)
print(f'Você digitou os valores ({digitados})')
print(f'O valor 9 apareceu {digitados.count(9)} vezes')
print(f'O valor 3 apareceu na {digitados.count(3)} posição')
print(f'Os valores pares digitados foram {}')

