usuario_pergunta = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(usuario_pergunta))
print('Só tem espaços? ', usuario_pergunta.isspace())
print('É um número? ', usuario_pergunta.isnumeric())
print('É alfabético? ', usuario_pergunta.isalpha())
print('É alfanumérico? ', usuario_pergunta.isalnum())
print('Está em maiúsculas? ', usuario_pergunta.isupper())
print('Está em minúsculas? ', usuario_pergunta.islower())
print('Está capitalizada? ', usuario_pergunta.istitle())